### PR TITLE
Awesome Books - Day 1

### PR DESCRIPTION
**Pull request by rudicarrilloypr**
### Project requirements

- Implement only a basic UI with plain HTML:

- Create a collection that keeps a list of books (hint: you can use an array of objects for that).
- Create a function to add a new book to the collection, with title and author.
- Create a function to remove a book from the collection (hint: you can use the [array filter()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) method).
- Display all books saved in the collection in the top part of the page.
- Make sure that when a user clicks the "Add" button:
  - A new book is added to the collection.
  - The new book is displayed in the page.
- Make sure that when a user clicks the "Remove" button:
  - The correct book is removed from the collection.
  - The correct book dissapears from the page.
- Make sure that data is preserved in the browser's memory by using [localStorage](https://github.com/microverseinc/curriculum-html-css/blob/main/local_storage.md).
- To debug your application, you can use [console.log()](https://developer.mozilla.org/en-US/docs/Web/API/Console/log). **Remember to remove debugging code before pushing your code to the remote repository.**
- Don't use any library or framework, use only plain JavaScript.

### CODE REVIEW

**Review by t-yanick — COMMENTED** [review]
# STATUS: INVALID SUBMISSION

Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not use the correct [Github flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)

- [ ] The Pull Request description is supposed to be a summary of what you did and not just copying pasting the project requirements

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rudicarrilloypr** [comment]
@t-yanick but that's what I did for the project

**Comment by t-yanick** [comment]
The pull request should be opened from the feature branch into the main branch.

**Comment by rudicarrilloypr** [comment]
@t-yanick that's what we did, the main branch is dev-day1

**Comment by t-yanick** [comment]
- [ ] Is the main branch supposed to be renamed? Kindly use the default name "main". Thanks
- [ ] Also review your pull request description

**Comment by rudicarrilloypr** [comment]
> * [x]  Is the main branch supposed to be renamed? Kindly use the default name "main". Thanks
> * [x]  Also review your pull request description

I cannot rename it because its a repository created by my partner, and I can't enter the settings of the repository, also I've always uploaded the project requirements as the pull request description, that's how a couple of mentors teached me, and I've all my projects aproved

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾🍾**
Hello @rudicarrilloypr and @EvansSnave 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR.
- Good commit messages.
- Correct git-flow.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
